// Render src/auth.ts: AuthConfig discriminated union + env/flag loaders +
// (when enabled) PKCE login flow against an oauth2 authorizationCode
// scheme. The login surface is rendered conditionally so specs without
// oauth2 don't pull in `open` / `node:http` / token-file machinery.

import type { Ir, OAuth2Flow, SecurityScheme } from '../types.js';

export interface OAuthEmitInputs {
  /** clientId from plugin config — required to enable the flow. */
  clientId: string;
  /** Loopback port; default 4747. Fallback range 4747–4757. */
  redirectPort: number;
  /** Override default scopes; falls back to spec-declared if empty. */
  scopes: string[];
  /** Pulled from `OAuth2Flow.authorization_url`. */
  authorizationUrl: string;
  /** Pulled from `OAuth2Flow.token_url`. */
  tokenUrl: string;
  /** Falls back to `tokenUrl` if the spec didn't declare one. */
  refreshUrl: string;
  /** Bin name — used for the platform config dir path. */
  binName: string;
}

export interface AuthInputs {
  envPrefix: string;       // e.g. "GITHUB" → GITHUB_TOKEN, GITHUB_API_KEY
  schemes: SecurityScheme[];
  /** When set, login/logout subcommands + token-file fallback are emitted. */
  oauth?: OAuthEmitInputs;
}

/** Find the first oauth2 scheme with an authorizationCode flow. */
export function findAuthCodeFlow(schemes: SecurityScheme[]): OAuth2Flow | undefined {
  for (const s of schemes) {
    if (s.kind.tag !== 'oauth2') continue;
    for (const f of s.kind.val.flows) {
      if (f.kind === 'authorization-code' && f.authorizationUrl && f.tokenUrl) {
        return f;
      }
    }
  }
  return undefined;
}

/** Union scopes referenced by any per-op security requirement that names
 *  an oauth2 scheme in the IR. Used as the default when config.oauth.scopes
 *  is empty. */
export function inferScopes(ir: Ir, schemes: SecurityScheme[]): string[] {
  const oauthIds = new Set(schemes.filter((s) => s.kind.tag === 'oauth2').map((s) => s.id));
  const found = new Set<string>();
  for (const op of ir.operations) {
    for (const req of op.security) {
      if (oauthIds.has(req.schemeId)) {
        for (const sc of req.scopes) found.add(sc);
      }
    }
  }
  return [...found].sort();
}

export function renderAuth(_ir: Ir, inp: AuthInputs): string {
  const supportedSchemes = inp.schemes.filter((s) =>
    s.kind.tag === 'api-key' || s.kind.tag === 'http-bearer' || s.kind.tag === 'http-basic',
  );

  const banner = `// Generated by openapi-forge — do not edit by hand.
//
// AuthConfig is a discriminated union covering the security schemes the
// spec declared (api-key, http-bearer, http-basic). \`loadAuth\` is async
// because the oauth2 path may need to refresh a stored token; on
// non-oauth flows the awaitable returns synchronously-equivalent.

`;

  const baseTypes = `export type AuthConfig =
  | { kind: "none" }
  | { kind: "apiKey"; name: string; in: "header" | "query" | "cookie"; key: string }
  | { kind: "bearer"; token: string }
  | { kind: "basic"; username: string; password: string };

export interface AuthFlags {
  token?: string;
  apiKey?: string;
  basic?: string; // "user:pass"
}

const ENV_PREFIX = ${JSON.stringify(inp.envPrefix)};

interface SchemeInfo {
  id: string;
  kind: "apiKey" | "bearer" | "basic";
  apiKeyName?: string;
  apiKeyIn?: "header" | "query" | "cookie";
}

const SCHEMES: SchemeInfo[] = ${JSON.stringify(supportedSchemes.map(schemeInfo), null, 2)};

`;

  const loadAuthBody = renderLoadAuth(inp);

  const applyAuthBlock = `/** Mutate \`headers\` and \`url\` for the configured auth. Returns the
 *  (possibly modified) URL — apiKey-in-query needs URL rewriting. */
export function applyAuth(auth: AuthConfig, headers: Record<string, string>, url: string): string {
  switch (auth.kind) {
    case "none":
      return url;
    case "bearer":
      headers["authorization"] = \`Bearer \${auth.token}\`;
      return url;
    case "basic": {
      const enc = Buffer.from(\`\${auth.username}:\${auth.password}\`, "utf8").toString("base64");
      headers["authorization"] = \`Basic \${enc}\`;
      return url;
    }
    case "apiKey":
      if (auth.in === "header") {
        headers[auth.name.toLowerCase()] = auth.key;
        return url;
      }
      if (auth.in === "query") {
        const sep = url.includes("?") ? "&" : "?";
        return \`\${url}\${sep}\${encodeURIComponent(auth.name)}=\${encodeURIComponent(auth.key)}\`;
      }
      // cookie
      headers["cookie"] = \`\${headers["cookie"] ? headers["cookie"] + "; " : ""}\${auth.name}=\${auth.key}\`;
      return url;
  }
}
`;

  const oauthBlock = inp.oauth ? renderOAuthBlock(inp.oauth) : '';

  return banner + baseTypes + loadAuthBody + applyAuthBlock + oauthBlock;
}

function renderLoadAuth(inp: AuthInputs): string {
  const oauthFallback = inp.oauth
    ? `
  // OAuth-stored token fallback (login flow ran previously).
  const stored = await loadStoredToken();
  if (stored) {
    const fresh = await refreshIfExpired(stored);
    if (fresh) return { kind: "bearer", token: fresh.access_token };
  }
`
    : '';

  return `export async function loadAuth(flags: AuthFlags): Promise<AuthConfig> {
  if (flags.token) return { kind: "bearer", token: flags.token };
  if (flags.apiKey) {
    const sc = SCHEMES.find((s) => s.kind === "apiKey");
    if (sc && sc.apiKeyName && sc.apiKeyIn) {
      return { kind: "apiKey", name: sc.apiKeyName, in: sc.apiKeyIn, key: flags.apiKey };
    }
  }
  if (flags.basic) {
    const idx = flags.basic.indexOf(":");
    if (idx >= 0) {
      return { kind: "basic", username: flags.basic.slice(0, idx), password: flags.basic.slice(idx + 1) };
    }
  }

  const envToken = process.env[\`\${ENV_PREFIX}_TOKEN\`];
  if (envToken) return { kind: "bearer", token: envToken };
${oauthFallback}
  const envKey = process.env[\`\${ENV_PREFIX}_API_KEY\`];
  if (envKey) {
    const sc = SCHEMES.find((s) => s.kind === "apiKey");
    if (sc && sc.apiKeyName && sc.apiKeyIn) {
      return { kind: "apiKey", name: sc.apiKeyName, in: sc.apiKeyIn, key: envKey };
    }
  }

  const envUser = process.env[\`\${ENV_PREFIX}_USERNAME\`];
  const envPass = process.env[\`\${ENV_PREFIX}_PASSWORD\`];
  if (envUser && envPass) return { kind: "basic", username: envUser, password: envPass };

  return { kind: "none" };
}

`;
}

function renderOAuthBlock(o: OAuthEmitInputs): string {
  // The whole block is one string template — escape every literal
  // backtick / `${` we don't want interpolated.
  return `
// ----- OAuth 2.0 Authorization Code Flow + PKCE ---------------------------
//
// Wired from the spec's oauth2 scheme + plugin config (clientId,
// redirectPort, scopes). PKCE is RFC 7636 with method S256; the loopback
// redirect follows RFC 8252 §7.3 (IPv4 literal, fixed-port-with-fallback).
// Token storage is file-based at the platform's standard config dir,
// mode 0600 on POSIX. Refresh is eager with a 60-second skew.

import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { createHash, randomBytes } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { homedir, platform } from "node:os";
import { dirname, join } from "node:path";

const OAUTH = {
  clientId: ${JSON.stringify(o.clientId)},
  authorizationUrl: ${JSON.stringify(o.authorizationUrl)},
  tokenUrl: ${JSON.stringify(o.tokenUrl)},
  refreshUrl: ${JSON.stringify(o.refreshUrl)},
  scopes: ${JSON.stringify(o.scopes)} as readonly string[],
  basePort: ${o.redirectPort},
  binName: ${JSON.stringify(o.binName)},
} as const;

interface StoredToken {
  access_token: string;
  token_type: string;
  expires_at: number;       // unix seconds
  refresh_token?: string;
  scope?: string;
  obtained_at: number;
}

function tokenPath(): string {
  const bin = OAUTH.binName;
  if (platform() === "darwin") {
    return join(homedir(), "Library", "Application Support", bin, "auth.json");
  }
  if (platform() === "win32") {
    const appdata = process.env["APPDATA"] ?? join(homedir(), "AppData", "Roaming");
    return join(appdata, bin, "auth.json");
  }
  const xdg = process.env["XDG_CONFIG_HOME"] ?? join(homedir(), ".config");
  return join(xdg, bin, "auth.json");
}

export async function loadStoredToken(): Promise<StoredToken | null> {
  const p = tokenPath();
  if (!existsSync(p)) return null;
  try {
    return JSON.parse(readFileSync(p, "utf8")) as StoredToken;
  } catch {
    return null;
  }
}

function saveStoredToken(t: StoredToken): void {
  const p = tokenPath();
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, JSON.stringify(t, null, 2), { encoding: "utf8", mode: 0o600 });
}

export async function logout(): Promise<boolean> {
  const p = tokenPath();
  if (!existsSync(p)) return false;
  rmSync(p, { force: true });
  return true;
}

let refreshInflight: Promise<StoredToken | null> | null = null;

export async function refreshIfExpired(t: StoredToken): Promise<StoredToken | null> {
  const now = Math.floor(Date.now() / 1000);
  if (t.expires_at - 60 > now) return t;
  if (!t.refresh_token) return null;
  if (refreshInflight) return refreshInflight;

  refreshInflight = (async () => {
    try {
      const body = new URLSearchParams({
        grant_type: "refresh_token",
        refresh_token: t.refresh_token!,
        client_id: OAUTH.clientId,
      });
      const res = await fetch(OAUTH.refreshUrl, {
        method: "POST",
        headers: { "content-type": "application/x-www-form-urlencoded" },
        body,
      });
      if (!res.ok) return null;
      const j = (await res.json()) as Record<string, unknown>;
      const access_token = String(j["access_token"] ?? "");
      if (!access_token) return null;
      const expires_in = typeof j["expires_in"] === "number" ? (j["expires_in"] as number) : 3600;
      const fresh: StoredToken = {
        access_token,
        token_type: String(j["token_type"] ?? t.token_type),
        expires_at: Math.floor(Date.now() / 1000) + expires_in,
        refresh_token: typeof j["refresh_token"] === "string" ? (j["refresh_token"] as string) : t.refresh_token,
        scope: typeof j["scope"] === "string" ? (j["scope"] as string) : t.scope,
        obtained_at: Date.now(),
      };
      saveStoredToken(fresh);
      return fresh;
    } finally {
      refreshInflight = null;
    }
  })();
  return refreshInflight;
}

function base64url(buf: Buffer): string {
  return buf.toString("base64").replace(/\\+/g, "-").replace(/\\//g, "_").replace(/=+$/, "");
}

function openBrowser(url: string): void {
  // Stay native: spawn the OS opener. Falls back to printing the URL on
  // failure — covers headless CI / SSH sessions.
  import("node:child_process")
    .then(({ spawn }) => {
      const cmd = platform() === "darwin" ? "open" : platform() === "win32" ? "start" : "xdg-open";
      const args = platform() === "win32" ? ["", url] : [url];
      const p = spawn(cmd, args, { stdio: "ignore", detached: true });
      p.on("error", () => process.stderr.write(\`Open this URL in a browser:\\n  \${url}\\n\`));
      p.unref();
    })
    .catch(() => process.stderr.write(\`Open this URL in a browser:\\n  \${url}\\n\`));
}

async function listenLoopback(): Promise<{ server: ReturnType<typeof createServer>; port: number; received: Promise<URLSearchParams> }> {
  // Try OAUTH.basePort, then fallback range basePort..basePort+10.
  for (let port = OAUTH.basePort; port < OAUTH.basePort + 11; port++) {
    let resolveReq!: (q: URLSearchParams) => void;
    let rejectReq!: (e: Error) => void;
    const received = new Promise<URLSearchParams>((res, rej) => {
      resolveReq = res;
      rejectReq = rej;
    });
    const server = createServer((req: IncomingMessage, res: ServerResponse) => {
      const url = new URL(req.url ?? "/", \`http://127.0.0.1:\${port}\`);
      if (url.pathname !== "/callback") {
        res.statusCode = 404;
        res.end("not found");
        return;
      }
      const err = url.searchParams.get("error");
      const html = err
        ? \`<!doctype html><h1>Login failed</h1><p><code>\${err}</code></p><p>You can close this tab.</p>\`
        : \`<!doctype html><h1>Login complete</h1><p>You can close this tab.</p><script>window.close()</script>\`;
      res.statusCode = err ? 400 : 200;
      res.setHeader("content-type", "text/html; charset=utf-8");
      res.end(html, () => {
        if (err) rejectReq(new Error(\`OAuth provider returned \${err}\`));
        else resolveReq(url.searchParams);
        server.close();
      });
    });
    const ok = await new Promise<boolean>((res) => {
      server.once("error", () => res(false));
      server.listen(port, "127.0.0.1", () => res(true));
    });
    if (ok) return { server, port, received };
  }
  throw new Error(
    \`Couldn't bind any loopback port in [\${OAUTH.basePort}, \${OAUTH.basePort + 10}]; ports in use.\`,
  );
}

export async function runLoginFlow(): Promise<StoredToken> {
  const code_verifier = base64url(randomBytes(64));
  const code_challenge = base64url(createHash("sha256").update(code_verifier).digest());
  const state = base64url(randomBytes(32));

  const { port, received } = await listenLoopback();
  const redirect_uri = \`http://127.0.0.1:\${port}/callback\`;

  const authUrl = new URL(OAUTH.authorizationUrl);
  authUrl.searchParams.set("response_type", "code");
  authUrl.searchParams.set("client_id", OAUTH.clientId);
  authUrl.searchParams.set("redirect_uri", redirect_uri);
  authUrl.searchParams.set("state", state);
  authUrl.searchParams.set("code_challenge", code_challenge);
  authUrl.searchParams.set("code_challenge_method", "S256");
  if (OAUTH.scopes.length > 0) authUrl.searchParams.set("scope", OAUTH.scopes.join(" "));

  process.stderr.write(\`Opening browser for OAuth login on \${redirect_uri}…\\n\`);
  openBrowser(authUrl.toString());

  // 5-minute window from RFC 8252 guidance.
  const params = await Promise.race([
    received,
    new Promise<URLSearchParams>((_, reject) =>
      setTimeout(() => reject(new Error("login timed out after 5 minutes")), 5 * 60_000),
    ),
  ]);
  if (params.get("state") !== state) throw new Error("OAuth state mismatch — possible CSRF; aborted");
  const code = params.get("code");
  if (!code) throw new Error("OAuth callback missing \`code\` parameter");

  const tokenRes = await fetch(OAUTH.tokenUrl, {
    method: "POST",
    headers: { "content-type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      grant_type: "authorization_code",
      code,
      client_id: OAUTH.clientId,
      redirect_uri,
      code_verifier,
    }),
  });
  if (!tokenRes.ok) {
    const text = await tokenRes.text().catch(() => "");
    throw new Error(\`Token exchange failed: \${tokenRes.status} \${tokenRes.statusText} \${text}\`);
  }
  const j = (await tokenRes.json()) as Record<string, unknown>;
  const access_token = String(j["access_token"] ?? "");
  if (!access_token) throw new Error("Token endpoint returned no \`access_token\`");
  const expires_in = typeof j["expires_in"] === "number" ? (j["expires_in"] as number) : 3600;
  const stored: StoredToken = {
    access_token,
    token_type: String(j["token_type"] ?? "Bearer"),
    expires_at: Math.floor(Date.now() / 1000) + expires_in,
    refresh_token: typeof j["refresh_token"] === "string" ? (j["refresh_token"] as string) : undefined,
    scope: typeof j["scope"] === "string" ? (j["scope"] as string) : undefined,
    obtained_at: Date.now(),
  };
  saveStoredToken(stored);
  return stored;
}
`;
}

function schemeInfo(s: SecurityScheme): {
  id: string;
  kind: 'apiKey' | 'bearer' | 'basic';
  apiKeyName?: string;
  apiKeyIn?: 'header' | 'query' | 'cookie';
} {
  switch (s.kind.tag) {
    case 'api-key':
      return { id: s.id, kind: 'apiKey', apiKeyName: s.kind.val.name, apiKeyIn: s.kind.val.in };
    case 'http-bearer':
      return { id: s.id, kind: 'bearer' };
    case 'http-basic':
      return { id: s.id, kind: 'basic' };
    case 'mutual-tls':
    case 'oauth2':
    case 'open-id-connect':
      // Filtered out before reaching here.
      throw new Error(`schemeInfo: ${s.kind.tag} not supported`);
  }
}
