// Render src/cli.ts: a commander.js Program with one subcommand per
// operation. Path params are positional, typed via commander argParser
// callbacks. Query / header / cookie params are `--<name>` flags. JSON
// request bodies expand into one `--<field>` flag per top-level required
// property; complex bodies fall back to `--body @file.json`.
//
// The output is intended to be ergonomically usable: every operation
// summary surfaces in `--help`, every enum gets `.choices()`, every
// description gets a help line.

import type { Ir, Operation, Parameter, NamedType } from '../types.js';
import { camelCase, kebabCase, pascalCase } from '../naming.js';
import { primitiveTs } from './models.js';

interface Ctx {
  byId: Map<string, NamedType>;
}

export interface CliInputs {
  binName: string;
  defaultBaseUrl: string;
  description: string;
  /** When true, register `login` and `logout` subcommands. The auth.ts
   *  module will already export `runLoginFlow` / `logout` because the
   *  same flag drove its conditional emission. */
  oauthEnabled: boolean;
}

export function renderCli(ir: Ir, inp: CliInputs): string {
  const ctx: Ctx = { byId: new Map(ir.types.map((t) => [t.id, t])) };

  const oauthImports = inp.oauthEnabled ? ', runLoginFlow, logout' : '';
  let out = `// Generated by openapi-forge — do not edit by hand.
import { Command, Option, InvalidArgumentError } from "commander";
import { readFileSync, readSync } from "node:fs";
import { ApiClient } from "./client.js";
import { loadAuth${oauthImports} } from "./auth.js";
import { ApiError } from "./runtime.js";
import { formatOutput, type OutputMode } from "./format.js";
import type * as M from "./models.js";

const program = new Command();
program
  .name(${JSON.stringify(inp.binName)})
  .description(${JSON.stringify(inp.description.trim() || inp.binName)})
  .version("${escape(ir.info.version)}")
  .showHelpAfterError()
  .enablePositionalOptions();

program
  .option("--base-url <url>", "API base URL", ${JSON.stringify(inp.defaultBaseUrl)})
  .option("--token <token>", "Bearer token (overrides env)")
  .option("--api-key <key>", "API key (overrides env)")
  .option("-u, --basic <user:pass>", "Basic auth (overrides env)")
  .addOption(new Option("--output <mode>", "Output mode").choices(["json", "compact", "table"]).default("json"));

`;

  if (inp.oauthEnabled) {
    out += `program
  .command("login")
  .description("Run OAuth 2.0 Authorization Code Flow with PKCE; persists the token at the platform config dir")
  .action(async () => {
    const stored = await runLoginFlow();
    process.stdout.write(stored.access_token + "\\n");
  });

program
  .command("logout")
  .description("Delete the stored OAuth token")
  .action(async () => {
    const removed = await logout();
    process.stderr.write(removed ? "logged out\\n" : "no stored token\\n");
  });

`;
  }

  for (const op of ir.operations) {
    out += renderSubcommand(ctx, op);
    out += '\n';
  }

  out += `program.parseAsync(process.argv).catch((err) => {
  if (err instanceof ApiError) {
    process.stderr.write(\`Status: \${err.status}\\n\`);
    process.stderr.write(typeof err.body === "string" ? err.body : JSON.stringify(err.body, null, 2));
    process.stderr.write("\\n");
    process.exit(Math.min(255, err.status));
  }
  process.stderr.write(String(err && (err.stack ?? err.message ?? err)) + "\\n");
  process.exit(1);
});

function readBodyArg(value: string | undefined): any {
  if (value === undefined) return undefined;
  if (value === "-") {
    const chunks: Buffer[] = [];
    const buf = Buffer.alloc(65536);
    while (true) {
      let n = 0;
      try { n = readSync(0, buf, 0, buf.length, null); } catch { break; }
      if (n <= 0) break;
      chunks.push(Buffer.from(buf.subarray(0, n)));
    }
    return JSON.parse(Buffer.concat(chunks).toString("utf8"));
  }
  if (value.startsWith("@")) {
    const path = value.slice(1);
    return JSON.parse(readFileSync(path, "utf8"));
  }
  // Inline JSON literal.
  return JSON.parse(value);
}

function parseInteger(v: string): number {
  const n = Number.parseInt(v, 10);
  if (Number.isNaN(n)) throw new InvalidArgumentError("not an integer");
  return n;
}

function parseFloat_(v: string): number {
  const n = Number.parseFloat(v);
  if (Number.isNaN(n)) throw new InvalidArgumentError("not a number");
  return n;
}

function parseBool(v: string): boolean {
  const t = v.toLowerCase();
  if (t === "true" || t === "1" || t === "yes") return true;
  if (t === "false" || t === "0" || t === "no") return false;
  throw new InvalidArgumentError("not a boolean (true/false/1/0/yes/no)");
}

function parseCsv(v: string, prev: string[] = []): string[] {
  return [...prev, ...v.split(",")];
}
`;

  return out;
}

function renderSubcommand(ctx: Ctx, op: Operation): string {
  const cmd = kebabCase(op.id);
  const summary = op.documentation?.split('\n')[0] ?? '';
  const methodName = camelCase(op.id);

  let out = `program
  .command(${JSON.stringify(cmd)})
  .description(${JSON.stringify(summary || op.id)})\n`;

  // Positional args for path params.
  for (const p of op.pathParams) {
    const argName = `<${kebabCase(p.name)}>`;
    const desc = p.documentation?.split('\n')[0] ?? `path parameter ${p.name}`;
    out += `  .argument(${JSON.stringify(argName)}, ${JSON.stringify(desc)})\n`;
  }

  // Body flag(s).
  if (op.requestBody) {
    if (op.requestBody.required) {
      out += `  .requiredOption("--body <json|@file|->" + ${JSON.stringify('')}, ${JSON.stringify('Request body: inline JSON, @file.json, or - for stdin')})\n`;
    } else {
      out += `  .option("--body <json|@file|->" + ${JSON.stringify('')}, ${JSON.stringify('Request body: inline JSON, @file.json, or - for stdin')})\n`;
    }
  }

  // Query / header / cookie flags.
  for (const p of [...op.queryParams, ...op.headerParams, ...op.cookieParams]) {
    out += renderOption(ctx, p);
  }

  // Action.
  const positionals = op.pathParams.map((p) => camelCase(p.name));
  out += `  .action(async (${positionals.length > 0 ? positionals.join(', ') + ', ' : ''}cmdOpts: any, cmd: any) => {
    const root = cmd.parent.opts();
    const auth = await loadAuth({ token: root.token, apiKey: root.apiKey, basic: root.basic });
    const client = new ApiClient({ baseUrl: root.baseUrl, auth });
    const opts: Record<string, unknown> = {};\n`;

  for (const p of [...op.queryParams, ...op.headerParams, ...op.cookieParams]) {
    const flag = camelCase(p.name);
    out += `    if (cmdOpts.${flag} !== undefined) opts[${JSON.stringify(flag)}] = ${convertCmdOptValue(ctx, p, `cmdOpts.${flag}`)};\n`;
  }

  // Build call args.
  const callArgs: string[] = [...positionals];
  if (op.requestBody) callArgs.push('readBodyArg(cmdOpts.body)');
  // The client method's `opts` parameter is precisely typed (a record
  // type with required / optional fields per the spec). At runtime we
  // collected it into `Record<string, unknown>`; commander's
  // requiredOption already enforced presence. Cast through `any` so
  // strict TS doesn't try to structurally prove the match.
  if ([...op.queryParams, ...op.headerParams, ...op.cookieParams].length > 0) callArgs.push('opts as any');

  out += `    const result = await client.${methodName}(${callArgs.join(', ')});
    if (result !== undefined) process.stdout.write(formatOutput(result, root.output as OutputMode) + "\\n");
  });\n`;

  return out;
}

function renderOption(ctx: Ctx, p: Parameter): string {
  const flag = `--${kebabCase(p.name)}`;
  const typeInfo = paramTypeInfo(ctx, p);
  const desc = p.documentation?.split('\n')[0] ?? `${(p as any).in ?? ''}${typeInfo.label ? ' (' + typeInfo.label + ')' : ''}`;
  const placeholder = typeInfo.array ? '<value...>' : `<${typeInfo.label}>`;
  const flagSpec = `${flag} ${placeholder}`;
  let line = `  .${p.required ? 'requiredOption' : 'option'}(${JSON.stringify(flagSpec)}, ${JSON.stringify(desc)}`;

  // commander argParser callback for type conversion.
  const parser = typeInfo.parser;
  if (parser) line += `, ${parser}`;
  line += `)\n`;

  // For string enums we use addOption + .choices(). Replace the line.
  if (typeInfo.choices) {
    const opt = `new Option(${JSON.stringify(flagSpec)}, ${JSON.stringify(desc)}).choices(${JSON.stringify(typeInfo.choices)})`;
    return `  .addOption(${p.required ? `${opt}.makeOptionMandatory()` : opt})\n`;
  }
  return line;
}

interface ParamTypeInfo {
  label: string;     // for placeholder
  parser?: string;   // commander argParser source
  choices?: string[];
  array: boolean;
}

function paramTypeInfo(ctx: Ctx, p: Parameter): ParamTypeInfo {
  const named = ctx.byId.get(p.type);
  if (!named) return { label: 'value', array: false };
  const def = named.definition;

  switch (def.tag) {
    case 'primitive': {
      const tsKind = primitiveTs(def.val);
      if (tsKind === 'number') {
        // Per #105 width info lives in `formatExtension` (`int32` /
        // `int64` / `float` / `double`). For CLI parsing we treat any
        // `integer` as an int (parseInt); `number` falls back to float.
        const isInt = def.val.kind === 'prim-integer';
        return { label: isInt ? 'int' : 'number', parser: isInt ? 'parseInteger' : 'parseFloat_', array: false };
      }
      if (tsKind === 'boolean') return { label: 'true|false', parser: 'parseBool', array: false };
      return { label: 'string', array: false };
    }
    case 'enum-string': {
      return { label: 'value', choices: def.val.values.map((v) => v.value), array: false };
    }
    case 'enum-int': {
      return { label: 'int', choices: def.val.values.map((v) => v.value.toString()), parser: 'parseInteger', array: false };
    }
    case 'array': {
      const inner = ctx.byId.get(def.val.items);
      const innerTs = inner && inner.definition.tag === 'primitive' ? primitiveTs(inner.definition.val) : 'value';
      return { label: innerTs, parser: 'parseCsv', array: true };
    }
    case 'object':
    case 'union':
      return { label: 'json', parser: undefined, array: false };
    case 'null':
      // Null parameters can only be the literal `null` on the wire; no
      // CLI parser needed.
      return { label: 'null', array: false };
  }
}

function convertCmdOptValue(ctx: Ctx, p: Parameter, valueExpr: string): string {
  const named = ctx.byId.get(p.type);
  if (!named) return valueExpr;
  const def = named.definition;
  if (def.tag === 'object' || def.tag === 'union') {
    return `JSON.parse(${valueExpr} as string)`;
  }
  if (def.tag === 'array') {
    // commander parseCsv collected strings; coerce numeric items if needed.
    const inner = ctx.byId.get(def.val.items);
    if (inner && inner.definition.tag === 'primitive') {
      const tsKind = primitiveTs(inner.definition.val);
      if (tsKind === 'number') return `(${valueExpr} as string[]).map(parseInteger)`;
      if (tsKind === 'boolean') return `(${valueExpr} as string[]).map(parseBool)`;
    }
    return valueExpr;
  }
  return valueExpr;
}

function escape(s: string): string {
  return s.replaceAll('\\', '\\\\').replaceAll('"', '\\"');
}

// Suppress unused-value lint on M import: pascalCase is used in models, not here.
export const _ignore = pascalCase;
