// Render src/client.ts: an ApiClient class with one async method per
// operation. Each method assembles URL + headers + body, calls fetch,
// and returns the parsed first 2xx JSON body — or throws ApiError on
// non-2xx, or returns the raw Response when a 2xx is non-JSON.

import type { Ir, Operation, Parameter, NamedType, BodyContent } from '../types.js';
import { camelCase, pascalCase } from '../naming.js';
import { primitiveTs } from './models.js';

interface Ctx {
  byId: Map<string, NamedType>;
}

export function renderClient(ir: Ir): string {
  const ctx: Ctx = { byId: new Map(ir.types.map((t) => [t.id, t])) };

  let out = `// Generated by openapi-forge — do not edit by hand.
import { applyAuth, type AuthConfig } from "./auth.js";
import type * as M from "./models.js";
import {
  ApiError,
  appendQueryDeepObject,
  appendQueryDelimited,
  appendQueryForm,
  joinUrl,
  type RequestOptions,
} from "./runtime.js";

export interface ApiClientOptions {
  baseUrl: string;
  auth?: AuthConfig;
  fetchImpl?: typeof globalThis.fetch;
}

export class ApiClient {
  private readonly baseUrl: string;
  private readonly auth: AuthConfig;
  private readonly fetchImpl: typeof globalThis.fetch;

  constructor(opts: ApiClientOptions) {
    this.baseUrl = opts.baseUrl;
    this.auth = opts.auth ?? { kind: "none" };
    this.fetchImpl = opts.fetchImpl ?? globalThis.fetch.bind(globalThis);
  }

`;

  for (const op of ir.operations) {
    out += renderOperation(ctx, op);
    out += '\n';
  }
  out += '}\n';
  return out;
}

function renderOperation(ctx: Ctx, op: Operation): string {
  const methodName = camelCase(op.id);
  const params = methodParams(ctx, op);
  const returnType = pickReturnType(ctx, op);

  const docLines: string[] = [];
  if (op.documentation) docLines.push(op.documentation);
  for (const p of [...op.pathParams, ...op.queryParams, ...op.headerParams]) {
    if (p.documentation) docLines.push(`@param ${camelCase(p.name)} ${p.documentation}`);
  }
  if (op.deprecated) docLines.push('@deprecated');
  const doc = jsDoc(docLines.join('\n'));

  let body = `  ${doc}async ${methodName}(${params.signature}): Promise<${returnType.ts}> {\n`;
  body += assembleUrl(op);
  body += assembleHeaders(op);
  body += assembleBody(op);
  body += sendRequest(op, returnType);
  body += `  }\n`;
  return body;
}

interface ReturnInfo {
  ts: string;
  parsing: 'json' | 'response';
}

function pickReturnType(ctx: Ctx, op: Operation): ReturnInfo {
  // First 2xx (or range) JSON content → its type as the return value.
  // Else any 2xx with non-JSON content → raw `Response`.
  // Else `void`.
  for (const r of op.responses) {
    if (!is2xxStatus(r.status)) continue;
    const json = r.content.find((c) => isJsonMedia(c.mediaType));
    if (json) {
      return { ts: typeRefToTs(ctx, json.type), parsing: 'json' };
    }
    if (r.content.length > 0) {
      return { ts: 'Response', parsing: 'response' };
    }
  }
  return { ts: 'void', parsing: 'json' };
}

function is2xxStatus(s: { tag: string; val?: unknown }): boolean {
  if (s.tag === 'explicit') return (s as any).val >= 200 && (s as any).val < 300;
  if (s.tag === 'range') return (s as any).val === 2;
  return false;
}

function isJsonMedia(m: string): boolean {
  return m === 'application/json' || m.endsWith('+json');
}

interface ParamSig {
  signature: string;
}

function methodParams(ctx: Ctx, op: Operation): ParamSig {
  const parts: string[] = [];
  for (const p of op.pathParams) parts.push(paramDecl(ctx, p, true));
  if (op.requestBody) {
    const c = pickRequestContent(op.requestBody.content);
    if (c) {
      const ts = bodyTypeTs(ctx, c);
      const optional = !op.requestBody.required ? '?' : '';
      parts.push(`body${optional}: ${ts}`);
    }
  }
  // Query / header / cookie params bundled into a single optional object.
  const queryHeaderCookie = [...op.queryParams, ...op.headerParams, ...op.cookieParams];
  if (queryHeaderCookie.length > 0) {
    const fields = queryHeaderCookie
      .map((p) => `${camelCase(p.name)}${p.required ? '' : '?'}: ${typeRefToTs(ctx, p.type)}`)
      .join('; ');
    const allOptional = queryHeaderCookie.every((p) => !p.required);
    parts.push(`opts${allOptional ? '?' : ''}: { ${fields} }`);
  }
  parts.push('reqOpts?: RequestOptions');
  return { signature: parts.join(', ') };
}

function paramDecl(ctx: Ctx, p: Parameter, _path: boolean): string {
  const t = typeRefToTs(ctx, p.type);
  return `${camelCase(p.name)}: ${t}`;
}

function typeRefToTs(ctx: Ctx, ref: string): string {
  const named = ctx.byId.get(ref);
  if (!named) return 'unknown';
  if (named.definition.tag === 'primitive') {
    return primitiveTs(named.definition.val);
  }
  if (named.definition.tag === 'null') {
    return 'null';
  }
  return `M.${pascalCase(named.id)}`;
}

function pickRequestContent(content: BodyContent[]): BodyContent | undefined {
  // Prefer JSON; fall back to first content. Out of scope for v1: per-op
  // overload selection by media type.
  return content.find((c) => isJsonMedia(c.mediaType)) ?? content[0];
}

function bodyTypeTs(ctx: Ctx, c: BodyContent): string {
  if (isJsonMedia(c.mediaType)) return typeRefToTs(ctx, c.type);
  if (c.mediaType.startsWith('text/')) return 'string';
  if (c.mediaType === 'application/octet-stream') return 'Uint8Array | ArrayBuffer | Blob';
  return 'unknown';
}

function assembleUrl(op: Operation): string {
  // Substitute `{placeholder}` with `encodeURIComponent(...)` only when
  // the spec actually declared a path-param with that name. Specs in the
  // wild sometimes have stray placeholders — leave those literal so the
  // generated TS still compiles. (Calling code can splice the brace
  // value via the URL param itself if it cares.)
  const declared = new Set(op.pathParams.map((p) => p.name));

  let lit = '';
  let i = 0;
  while (i < op.pathTemplate.length) {
    const open = op.pathTemplate.indexOf('{', i);
    if (open < 0) {
      lit += escapeBackticks(op.pathTemplate.slice(i));
      break;
    }
    lit += escapeBackticks(op.pathTemplate.slice(i, open));
    const close = op.pathTemplate.indexOf('}', open);
    if (close < 0) {
      lit += escapeBackticks(op.pathTemplate.slice(open));
      break;
    }
    const placeholder = op.pathTemplate.slice(open + 1, close);
    if (declared.has(placeholder)) {
      lit += '${encodeURIComponent(String(' + camelCase(placeholder) + '))}';
    } else {
      lit += escapeBackticks(op.pathTemplate.slice(open, close + 1));
    }
    i = close + 1;
  }
  let out = `    let url = joinUrl(this.baseUrl, \`${lit}\`);\n`;

  // Append query params per style.
  for (const p of op.queryParams) {
    const arg = `opts.${camelCase(p.name)}`;
    out += `    if (opts && ${arg} !== undefined) {\n`;
    switch (p.style) {
      case 'pipe-delimited':
        out += `      url = appendQueryDelimited(url, ${JSON.stringify(p.name)}, ${arg} as readonly unknown[], "|");\n`;
        break;
      case 'space-delimited':
        out += `      url = appendQueryDelimited(url, ${JSON.stringify(p.name)}, ${arg} as readonly unknown[], " ");\n`;
        break;
      case 'deep-object':
        out += `      url = appendQueryDeepObject(url, ${JSON.stringify(p.name)}, ${arg} as Record<string, unknown>);\n`;
        break;
      default:
        out += `      url = appendQueryForm(url, ${JSON.stringify(p.name)}, ${arg}, ${p.explode});\n`;
        break;
    }
    out += `    }\n`;
  }
  return out;
}

function assembleHeaders(op: Operation): string {
  let out = `    const headers: Record<string, string> = { ...(reqOpts?.headers ?? {}) };\n`;
  for (const p of op.headerParams) {
    const arg = `opts.${camelCase(p.name)}`;
    out += `    if (opts && ${arg} !== undefined) headers[${JSON.stringify(p.name.toLowerCase())}] = String(${arg});\n`;
  }
  for (const p of op.cookieParams) {
    const arg = `opts.${camelCase(p.name)}`;
    out += `    if (opts && ${arg} !== undefined) {\n`;
    out += `      const cookie = headers["cookie"] ? headers["cookie"] + "; " : "";\n`;
    out += `      headers["cookie"] = cookie + ${JSON.stringify(p.name)} + "=" + encodeURIComponent(String(${arg}));\n`;
    out += `    }\n`;
  }
  out += `    url = applyAuth(this.auth, headers, url);\n`;
  return out;
}

function assembleBody(op: Operation): string {
  if (!op.requestBody) {
    return `    const init: RequestInit = { method: ${JSON.stringify(op.method.toUpperCase())}, headers, signal: reqOpts?.signal };\n`;
  }
  const c = pickRequestContent(op.requestBody.content);
  if (!c) {
    return `    const init: RequestInit = { method: ${JSON.stringify(op.method.toUpperCase())}, headers, signal: reqOpts?.signal };\n`;
  }
  let out = '';
  if (isJsonMedia(c.mediaType)) {
    out += `    const init: RequestInit = {\n`;
    out += `      method: ${JSON.stringify(op.method.toUpperCase())},\n`;
    out += `      headers: { ...headers, "content-type": "application/json" },\n`;
    out += `      body: body !== undefined ? JSON.stringify(body) : undefined,\n`;
    out += `      signal: reqOpts?.signal,\n`;
    out += `    };\n`;
  } else if (c.mediaType.startsWith('text/')) {
    out += `    const init: RequestInit = {\n`;
    out += `      method: ${JSON.stringify(op.method.toUpperCase())},\n`;
    out += `      headers: { ...headers, "content-type": ${JSON.stringify(c.mediaType)} },\n`;
    out += `      body: body as string,\n`;
    out += `      signal: reqOpts?.signal,\n`;
    out += `    };\n`;
  } else if (c.mediaType === 'application/octet-stream') {
    out += `    const init: RequestInit = {\n`;
    out += `      method: ${JSON.stringify(op.method.toUpperCase())},\n`;
    out += `      headers: { ...headers, "content-type": "application/octet-stream" },\n`;
    out += `      body: body as Uint8Array | ArrayBuffer | Blob,\n`;
    out += `      signal: reqOpts?.signal,\n`;
    out += `    };\n`;
  } else {
    out += `    const init: RequestInit = {\n`;
    out += `      method: ${JSON.stringify(op.method.toUpperCase())},\n`;
    out += `      headers: { ...headers, "content-type": ${JSON.stringify(c.mediaType)} },\n`;
    out += `      body: body as never as RequestInit['body'],\n`;
    out += `      signal: reqOpts?.signal,\n`;
    out += `    };\n`;
  }
  return out;
}

function sendRequest(_op: Operation, ret: ReturnInfo): string {
  let out = `    const res = await this.fetchImpl(url, init);\n`;
  out += `    if (!res.ok) throw await ApiError.fromResponse(res);\n`;
  if (ret.ts === 'void') {
    out += `    return;\n`;
  } else if (ret.parsing === 'response') {
    out += `    return res;\n`;
  } else {
    out += `    return (await res.json()) as ${ret.ts};\n`;
  }
  return out;
}

function escapeBackticks(s: string): string {
  return s.replaceAll('`', '\\`').replaceAll('${', '\\${');
}

function jsDoc(text: string | undefined): string {
  if (!text) return '';
  const lines = text.trim().split('\n');
  if (lines.length === 1) return `/** ${lines[0]} */\n  `;
  const body = lines.map((l) => `   * ${l}`).join('\n');
  return `/**\n${body}\n   */\n  `;
}
