// Render src/models.ts: one TS declaration per IR named-type. Topological
// order is preserved by the parser, so emitting in `ir.types` order never
// references a name before declaration.

import type {
  Ir,
  NamedType,
  PrimitiveType,
  TypeDef,
  TypeRef,
  ObjectType,
  EnumStringType,
  EnumIntType,
  UnionType,
  ArrayType,
} from '../types.js';
import { pascalCase, camelCase } from '../naming.js';

interface Ctx {
  byId: Map<string, NamedType>;
}

export function renderModels(ir: Ir): string {
  const ctx: Ctx = { byId: new Map(ir.types.map((t) => [t.id, t])) };

  let out = '// Generated by openapi-forge — do not edit by hand.\n\n';
  for (const t of ir.types) {
    out += renderNamedType(ctx, t);
    out += '\n';
  }
  return out;
}

function renderNamedType(ctx: Ctx, t: NamedType): string {
  const name = pascalCase(t.id);
  const doc = jsDoc(t.documentation);

  switch (t.definition.tag) {
    case 'primitive': {
      const ts = primitiveTs(t.definition.val);
      return `${doc}export type ${name} = ${ts};\n`;
    }
    case 'array': {
      return renderArrayAlias(ctx, name, doc, t.definition.val);
    }
    case 'enum-string': {
      return renderEnumString(name, doc, t.definition.val);
    }
    case 'enum-int': {
      return renderEnumInt(name, doc, t.definition.val);
    }
    case 'object': {
      return renderInterface(ctx, name, doc, t.definition.val);
    }
    case 'union': {
      return renderUnion(ctx, name, doc, t.definition.val);
    }
    case 'null': {
      // Skip the canonical Null singleton (id `"null"`); a user-named Null
      // alias (`components.schemas.Foo: { type: "null" }`) renders to a
      // top-level `type Foo = null;`. Issue #107.
      if (t.id === 'null') return '';
      return `${doc}export type ${name} = null;\n`;
    }
  }
}

function renderArrayAlias(ctx: Ctx, name: string, doc: string, a: ArrayType): string {
  const item = typeRefToTs(ctx, a.items);
  return `${doc}export type ${name} = ${item}[];\n`;
}

function renderEnumString(name: string, doc: string, e: EnumStringType): string {
  const cases = e.values.map((v) => JSON.stringify(v.value)).join(' | ');
  const inner = cases || 'never';
  return `${doc}export type ${name} = ${inner};\n`;
}

function renderEnumInt(name: string, doc: string, e: EnumIntType): string {
  const cases = e.values.map((v) => v.value.toString()).join(' | ');
  const inner = cases || 'never';
  return `${doc}export type ${name} = ${inner};\n`;
}

function renderInterface(ctx: Ctx, name: string, doc: string, o: ObjectType): string {
  let body = '';
  for (const p of o.properties) {
    // Use the spec's original property name verbatim — preserves wire
    // fidelity (`+1`, `-1`, `kebab-case-keys`) and avoids the collisions
    // that camelCase produces on operators (e.g. `+1` and `-1` both →
    // `_1`). TS supports quoted property keys; consumers access via
    // `obj["+1"]`.
    const key = jsObjectKey(p.name);
    const t = typeRefToTs(ctx, p.type);
    const ann = p.required ? '' : '?';
    const docLine = jsDoc(propertyDoc(p));
    body += `  ${docLine}${key}${ann}: ${t};\n`;
  }
  if (o.additionalProperties.tag === 'typed') {
    const v = typeRefToTs(ctx, o.additionalProperties.val);
    body += `  [extra: string]: ${v};\n`;
  } else if (o.additionalProperties.tag === 'any') {
    body += `  [extra: string]: unknown;\n`;
  }
  return `${doc}export interface ${name} {\n${body}}\n`;
}

function renderUnion(ctx: Ctx, name: string, doc: string, u: UnionType): string {
  if (u.variants.length === 0) {
    return `${doc}export type ${name} = never;\n`;
  }
  const cases: string[] = [];
  if (u.discriminator) {
    const propRaw = u.discriminator.propertyName;
    const propName = camelCase(propRaw);
    const mapping = new Map(u.discriminator.mapping);
    for (const v of u.variants) {
      // The Null variant (issue #107) renders as the literal `null`
      // rather than going through pascalCase + the discriminator tag,
      // since nullability is structural — not discriminated.
      if (isNullTypeRef(ctx, v.type)) {
        cases.push('null');
        continue;
      }
      const tag = findDiscriminatorTag(v.type, v.name, mapping);
      const tname = pascalCase(v.type);
      cases.push(`{ ${propName}: ${JSON.stringify(tag)} } & ${tname}`);
    }
  } else {
    for (const v of u.variants) {
      if (isNullTypeRef(ctx, v.type)) {
        cases.push('null');
        continue;
      }
      cases.push(pascalCase(v.type));
    }
  }
  return `${doc}export type ${name} =\n  | ${cases.join('\n  | ')};\n`;
}

function isNullTypeRef(ctx: Ctx, ref: TypeRef): boolean {
  const named = ctx.byId.get(ref);
  return !!named && named.definition.tag === 'null';
}

function findDiscriminatorTag(
  variantType: TypeRef,
  variantName: string | undefined,
  mapping: Map<string, TypeRef>,
): string {
  // Reverse lookup: which key maps to this type-ref?
  for (const [k, v] of mapping) {
    if (v === variantType) return k;
  }
  // Fall back to the explicit `name` on the union variant; finally the
  // type-ref id itself.
  return variantName ?? variantType;
}

export function typeRefToTs(ctx: Ctx, ref: TypeRef): string {
  const named = ctx.byId.get(ref);
  if (!named) {
    // Synthetic refs that don't resolve fall back to `unknown`. The host
    // will warn separately on dangling refs; this keeps emit moving.
    return 'unknown';
  }
  return primitiveOrName(named);
}

// For property and parameter types, when the named-type is a one-line alias
// (primitive, simple array of primitive) we *could* inline it, but
// preserving the alias name keeps the output greppable and matches the
// pattern in the existing TS-fetch generator.
function primitiveOrName(t: NamedType): string {
  return pascalCase(t.id);
}

export function primitiveTs(p: PrimitiveType): string {
  // Per #105 the IR carries the JSON Schema `type` value only; format
  // refinements (date / date-time / uuid / int32 / decimal / byte / …)
  // live on `formatExtension`. JS doesn't distinguish int widths, so
  // all numerics collapse to `number`.
  const fmt = p.constraints.formatExtension;
  switch (p.kind) {
    case 'prim-string':
      // `byte` (base64 in JSON) and `binary` (raw bytes in raw bodies)
      // both render as `string` here — the CLI generator emits typings,
      // not runtime decoders. Plugins that produce `Uint8Array` for
      // binary fields would key off the same `formatExtension`.
      return 'string';
    case 'prim-integer':
    case 'prim-number':
      return 'number';
    case 'prim-bool':
      return 'boolean';
  }
  // Unused branch to keep TS narrowing honest; hint the format slot is
  // available for richer future generators.
  void fmt;
  return 'unknown';
}

// JSDoc helpers ------------------------------------------------------------

function jsDoc(text: string | undefined): string {
  if (!text) return '';
  const lines = text.trim().split('\n');
  if (lines.length === 1) return `/** ${escapeForBlockComment(lines[0]!)} */\n`;
  const body = lines.map((l) => ` * ${escapeForBlockComment(l)}`).join('\n');
  return `/**\n${body}\n */\n`;
}

function propertyDoc(p: { documentation?: string; deprecated: boolean; readOnly: boolean; writeOnly: boolean }): string | undefined {
  const parts: string[] = [];
  if (p.documentation) parts.push(p.documentation);
  if (p.deprecated) parts.push('@deprecated');
  if (p.readOnly) parts.push('@readonly');
  if (p.writeOnly) parts.push('@writeonly');
  return parts.length === 0 ? undefined : parts.join('\n');
}

function escapeForBlockComment(s: string): string {
  return s.replaceAll('*/', '*\\/');
}

// JS object property key. Bare identifier if the spec name is a valid JS
// identifier and not reserved; otherwise quoted.
function jsObjectKey(name: string): string {
  if (/^[A-Za-z_$][\w$]*$/.test(name) && !TS_RESERVED.has(name)) return name;
  return JSON.stringify(name);
}

// Subset of TS reserved words that can't appear as bare object keys
// without TS complaining (most keywords actually *can* be used as keys,
// but 'enum' / 'class' / etc. are clearer with quotes).
const TS_RESERVED = new Set<string>([
  'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger', 'default',
  'delete', 'do', 'else', 'enum', 'export', 'extends', 'false', 'finally', 'for',
  'function', 'if', 'import', 'in', 'instanceof', 'new', 'null', 'return',
  'super', 'switch', 'this', 'throw', 'true', 'try', 'typeof', 'var', 'void',
  'while', 'with',
]);
// Forward unused warning (TypeDef referenced for completeness above).
export type _ = TypeDef;
